### Import Libraries

In [24]:
import pandas as pd
import numpy as np
import os

###  Load the Cleaned Dataset

In [25]:
data_path = '../data/processed/cleaned_data.csv' if os.path.exists('../data/processed/cleaned_data.csv') else 'data/processed/cleaned_data.csv'
df = pd.read_csv(data_path)

print(f'Dataset Loaded: {df.shape[0]} rows, {df.shape[1]} columns')
df.head()

Dataset Loaded: 32409 rows, 12 columns

,age,income,home_ownership,employment_years,loan_purpose,loan_grade,loan_amount,interest_rate,default,loan_income_ratio,previous_default,credit_history_years
0,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
1,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
2,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
3,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
4,21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2

###  Loan-to-Income (LTI) Ratio

In [26]:
df['loan_to_income'] = (df['loan_amount'] / df['income']).round(4)

print('Loan-to-Income Summary:')
print(df['loan_to_income'].describe().round(4))
df[['loan_amount', 'income', 'loan_to_income']].head()

Loan-to-Income Summary:
count    32409.0000
mean         0.1706
std          0.1071
min          0.0008
25%          0.0897
50%          0.1481
75%          0.2292
max          0.8300
Name: loan_to_income, dtype: float64

   loan_amount  income  loan_to_income
0         1000    9600          0.1042
1         5500    9600          0.5729
2        35000   65500          0.5344
3        35000   54400          0.6434
4         2500    9900          0.2525

###  Remaining Annual Disposable Income

In [27]:
df['remaining_income'] = df['income'] - df['loan_amount']

print('Remaining Income Summary:')
print(df['remaining_income'].describe().round(2))
df[['income', 'loan_amount', 'remaining_income']].head()

Remaining Income Summary:
count      32409.00
mean       56301.79
std        50870.38
min         1450.00
25%        30350.00
50%        46000.00
75%        68000.00
max      2031334.00
Name: remaining_income, dtype: float64

   income  loan_amount  remaining_income
0    9600         1000              8600
1    9600         5500              4100
2   65500        35000             30500
3   54400        35000             19400
4    9900         2500              7400

### Estimated Annual Interest Payment

In [28]:
df['annual_interest_payment'] = (df['loan_amount'] * (df['interest_rate'] / 100)).round(2)

print('Annual Interest Payment Summary:')
print(df['annual_interest_payment'].describe().round(2))
df[['loan_amount', 'interest_rate', 'annual_interest_payment']].head()

Annual Interest Payment Summary:
count    32409.00
mean      1086.02
std        874.46
min         37.45
25%        478.06
50%        822.00
75%       1423.20
max       7087.50
Name: annual_interest_payment, dtype: float64

   loan_amount  interest_rate  annual_interest_payment
0         1000          11.14                   111.40
1         5500          12.87                   707.85
2        35000          15.23                  5330.50
3        35000          14.27                  4994.50
4         2500           7.14                   178.50

###  Estimated Monthly Debt Payment

In [29]:
df['estimated_monthly_payment'] = ((df['loan_amount'] + (df['annual_interest_payment'] * 3)) / 36).round(2)

print('Estimated Monthly Payment Summary:')
print(df['estimated_monthly_payment'].describe().round(2))
df[['loan_amount', 'interest_rate', 'estimated_monthly_payment']].head()

Estimated Monthly Payment Summary:
count    32409.00
mean       356.96
std        243.47
min         17.01
25%        180.85
50%        298.82
75%        468.13
max       1562.85
Name: estimated_monthly_payment, dtype: float64

   loan_amount  interest_rate  estimated_monthly_payment
0         1000          11.14                      37.06
1         5500          12.87                     211.77
2        35000          15.23                    1416.43
3        35000          14.27                    1388.43
4         2500           7.14                      84.32

### Monthly Debt Payment to Monthly Income Ratio (DTI)

In [30]:
df['monthly_debt_to_income'] = (df['estimated_monthly_payment'] / (df['income'] / 12)).round(4)

print('Monthly Debt-to-Income Summary:')
print(df['monthly_debt_to_income'].describe().round(4))
df[['estimated_monthly_payment', 'income', 'monthly_debt_to_income']].head()

Monthly Debt-to-Income Summary:
count    32409.0000
mean         0.0761
std          0.0489
min          0.0003
25%          0.0390
50%          0.0653
75%          0.1025
max          0.3577
Name: monthly_debt_to_income, dtype: float64

   estimated_monthly_payment  income  monthly_debt_to_income
0                      37.06    9600                  0.0463
1                     211.77    9600                  0.2647
2                    1416.43   65500                  0.2595
3                    1388.43   54400                  0.3063
4                      84.32    9900                  0.1022

###  Credit History to Age Ratio

In [31]:
df['credit_to_age_ratio'] = (df['credit_history_years'] / df['age']).round(4)

print('Credit History to Age Ratio Summary:')
print(df['credit_to_age_ratio'].describe().round(4))
df[['credit_history_years', 'age', 'credit_to_age_ratio']].head()

Credit History to Age Ratio Summary:
count    32409.0000
mean         0.1949
std          0.0936
min          0.0769
25%          0.1250
50%          0.1739
75%          0.2619
max          0.5882
Name: credit_to_age_ratio, dtype: float64

   credit_history_years  age  credit_to_age_ratio
0                     2   21               0.0952
1                     3   25               0.1200
2                     2   23               0.0870
3                     4   24               0.1667
4                     2   21               0.0952

### Employment Length to Age Ratio

In [32]:
df['emp_to_age_ratio'] = (df['employment_years'] / df['age']).round(4)

print('Employment to Age Ratio Summary:')
print(df['emp_to_age_ratio'].describe().round(4))
df[['employment_years', 'age', 'emp_to_age_ratio']].head()

Employment to Age Ratio Summary:
count    32409.0000
mean         0.1734
std          0.1335
min          0.0000
25%          0.0667
50%          0.1481
75%          0.2727
max          0.7170
Name: emp_to_age_ratio, dtype: float64

   employment_years  age  emp_to_age_ratio
0               5.0   21            0.2381
1               1.0   25            0.0400
2               4.0   23            0.1739
3               8.0   24            0.3333
4               2.0   21            0.0952

###  Loan Amount per Employment Year

In [33]:
df['loan_per_emp_year'] = (df['loan_amount'] / (df['employment_years'] + 1)).round(2)

print('Loan per Employment Year Summary:')
print(df['loan_per_emp_year'].describe().round(2))
df[['loan_amount', 'employment_years', 'loan_per_emp_year']].head()

Loan per Employment Year Summary:
count    32409.00
mean      2846.44
std       3466.95
min         45.45
25%        888.89
50%       1666.67
75%       3333.33
max      35000.00
Name: loan_per_emp_year, dtype: float64

   loan_amount  employment_years  loan_per_emp_year
0         1000               5.0             166.67
1         5500               1.0            2750.00
2        35000               4.0            7000.00
3        35000               8.0            3888.89
4         2500               2.0             833.33

###  High Debt Burden (> 30% of Income)

In [34]:
df['high_debt_flag'] = (df['loan_income_ratio'] > 0.30).astype(int)

print('High Debt Burden Count (0 = Normal, 1 = High Debt):')
print(df['high_debt_flag'].value_counts())

High Debt Burden Count (0 = Normal, 1 = High Debt):
high_debt_flag
0    28591
1     3818
Name: count, dtype: int64

###  High Interest Rate (> 15%)

In [35]:
df['high_interest_flag'] = (df['interest_rate'] > 15.0).astype(int)

print('High Interest Flag Count (0 = <=15%, 1 = >15%):')
print(df['high_interest_flag'].value_counts())

High Interest Flag Count (0 = <=15%, 1 = >15%):
high_interest_flag
0    28551
1     3858
Name: count, dtype: int64

###  Previous Default Indicator

In [36]:
df['has_previous_default'] = (df['previous_default'] == 'Y').astype(int)

print('Previous Default Binary Count (0 = Clean Record, 1 = Past Default):')
print(df['has_previous_default'].value_counts())

Previous Default Binary Count (0 = Clean Record, 1 = Past Default):
has_previous_default
0    26680
1     5729
Name: count, dtype: int64

### Young Borrower Flag (Age < 25)

In [37]:
df['is_young_borrower'] = (df['age'] < 25).astype(int)

print('Young Borrower Count (0 = 25+, 1 = Under 25):')
print(df['is_young_borrower'].value_counts())

Young Borrower Count (0 = 25+, 1 = Under 25):
is_young_borrower
0    20189
1    12220
Name: count, dtype: int64

### Log Transformations for Skewed Financial Features

In [38]:
df['log_income'] = np.log1p(df['income']).round(4)
df['log_loan_amount'] = np.log1p(df['loan_amount']).round(4)

print('Log Transformation Summary:')
print(df[['income', 'log_income', 'loan_amount', 'log_loan_amount']].head())

Log Transformation Summary:
   income  log_income  loan_amount  log_loan_amount
0    9600      9.1696         1000           6.9088
1    9600      9.1696         5500           8.6127
2   65500     11.0898        35000          10.4631
3   54400     10.9041        35000          10.4631
4    9900      9.2004         2500           7.8244

###  Age Group Cohort Bins

In [39]:
df['age_group'] = pd.cut(
    df['age'],
    bins=[17, 25, 40, 60, 100],
    labels=['Young', 'Adult', 'Middle-Age', 'Senior']
)

print('Age Group Distribution:')
print(df['age_group'].value_counts())

Age Group Distribution:
age_group
Adult         15680
Young         15243
Middle-Age     1421
Senior           65
Name: count, dtype: int64

### Income Quartile Bins

In [40]:
df['income_quartile'] = pd.qcut(
    df['income'],
    q=4,
    labels=['Low Income', 'Medium Income', 'Upper Income', 'High Income']
)

print('Income Quartile Distribution:')
print(df['income_quartile'].value_counts())

Income Quartile Distribution:
income_quartile
Medium Income    8188
Low Income       8104
High Income      8099
Upper Income     8018
Name: count, dtype: int64

### Loan Size Categories

In [41]:
df['loan_size_category'] = pd.cut(
    df['loan_amount'],
    bins=[0, 5000, 15000, 25000, 100000],
    labels=['Small', 'Medium', 'Large', 'Jumbo']
)

print('Loan Size Category Distribution:')
print(df['loan_size_category'].value_counts())

Loan Size Category Distribution:
loan_size_category
Medium    18073
Small      9428
Large      4459
Jumbo       449
Name: count, dtype: int64

###  Ordinal Encoding - Loan Grade (A=1 to G=7)

In [42]:
grade_map = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7}
df['loan_grade_num'] = df['loan_grade'].map(grade_map)

print('Loan Grade Ordinal Mapping Sample:')
print(df[['loan_grade', 'loan_grade_num']].drop_duplicates().sort_values('loan_grade_num'))

Loan Grade Ordinal Mapping Sample:
    loan_grade  loan_grade_num
4            A               1
0            B               2
1            C               3
8            D               4
12           E               5
16           F               6
444          G               7

###  One-Hot Encoding for Categorical Features

In [43]:
dummies = pd.get_dummies(df[['home_ownership', 'loan_purpose']], drop_first=True, dtype=int)

print('One-Hot Encoded Features Created:')
print(list(dummies.columns))
dummies.head()

One-Hot Encoded Features Created:
['home_ownership_OTHER', 'home_ownership_OWN', 'home_ownership_RENT', 'loan_purpose_EDUCATION', 'loan_purpose_HOMEIMPROVEMENT', 'loan_purpose_MEDICAL', 'loan_purpose_PERSONAL', 'loan_purpose_VENTURE']

,home_ownership_OTHER,home_ownership_OWN,home_ownership_RENT,loan_purpose_EDUCATION,loan_purpose_HOMEIMPROVEMENT,loan_purpose_MEDICAL,loan_purpose_PERSONAL,loan_purpose_VENTURE
0,0,1,0,1,0,0,0,0
1,0,0,0,0,0,1,0,0
2,0,0,1,0,0,1,0,0
3,0,0,1,0,0,1,0,0
4,0,1,0,0,0,0,0,1

### Correlation of Engineered Features with Loan Default

In [44]:
numeric_cols = [
    'loan_to_income',
    'loan_income_ratio',
    'remaining_income',
    'annual_interest_payment',
    'estimated_monthly_payment',
    'monthly_debt_to_income',
    'credit_to_age_ratio',
    'emp_to_age_ratio',
    'loan_per_emp_year',
    'high_debt_flag',
    'high_interest_flag',
    'has_previous_default',
    'is_young_borrower',
    'loan_grade_num',
    'default'
]

corr_series = df[numeric_cols].corr()['default'].sort_values(ascending=False)
print('Correlation of Features with Default:')
print(corr_series.round(4))

Correlation of Features with Default:
default                      1.0000
high_debt_flag               0.4293
monthly_debt_to_income       0.4162
loan_to_income               0.3861
loan_income_ratio            0.3796
loan_grade_num               0.3734
high_interest_flag           0.3211
annual_interest_payment      0.2136
has_previous_default         0.1792
estimated_monthly_payment    0.1401
loan_per_emp_year            0.1195
is_young_borrower            0.0276
credit_to_age_ratio         -0.0173
emp_to_age_ratio            -0.0859
remaining_income            -0.1879
Name: default, dtype: float64

###  Save the Fully Featured Dataset

In [45]:
featured_path = '../data/processed/featured_data.csv' if os.path.exists('../data') else 'data/processed/featured_data.csv'
df.to_csv(featured_path, index=False)

print(f'Full Featured Data Saved to: {featured_path}')
print(f'Final Dimensions: {df.shape[0]} rows, {df.shape[1]} columns')

Full Featured Data Saved to: ../data/processed/featured_data.csv
Final Dimensions: 32409 rows, 30 columns

###  Save Baseline Model Dataset for Modeling Pipelines

In [46]:
model_cols = [
    'age',
    'income',
    'employment_years',
    'home_ownership',
    'loan_amount',
    'loan_purpose',
    'credit_history_years',
    'default'
]

model_df = df[model_cols].copy()
model_path = '../data/processed/model_data.csv' if os.path.exists('../data') else 'data/processed/model_data.csv'
model_df.to_csv(model_path, index=False)

print('=' * 60)
print(f'Model Dataset Successfully Saved to: {model_path}')
print(f'Dimensions: {model_df.shape[0]} rows, {model_df.shape[1]} columns')
print('=' * 60)

============================================================
Model Dataset Successfully Saved to: ../data/processed/model_data.csv
Dimensions: 32409 rows, 8 columns
============================================================